apiVersion: apps/v1
kind: Deployment
metadata:
  name: devtest
spec:
  replicas: 4
  selector:
    matchLabels:
      app: devtest
  template:
    metadata:
      labels:
        app: devtest
    spec:
      containers:
      - name: devtest
        image: ikericookies/devtestv1:416
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3000"
        - name: DATABASE
          value: "mongodb+srv://ayoolavictor415:<password>@cluster0.arqwy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: devtest-secrets
              key: DATABASE_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: devtest-secrets
              key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: devtest-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  selector:
    app: devtest
  ports:
  - protocol: TCP
    port: 80                
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devtest-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devtest
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
