apiVersion: apps/v1
kind: Deployment
metadata:
  name: devtest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devtest
  template:
    metadata:
      labels:
        app: devtest
    spec:
      containers:
      - name: devtest
        image: ikericookies/devtestv1:240
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: devtest-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  selector:
    app: devtest
  ports:
  - protocol: TCP
    port: 80                
    targetPort: 3000
  type: LoadBalancer
